package admin.api.metier.ejb;

// Generated 9 ao�t 2013 22:29:28 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VScriptupdateId generated by hbm2java
 */
@Embeddable
@SuppressWarnings("serial")
public class VScriptupdateId implements java.io.Serializable {

	private String url;
	private String driver;
	private String login;
	private String password;
	private String filename;
	private int id;
	private int id_1;
	private int id_2;

	public VScriptupdateId() {
	}

	public VScriptupdateId(int id, int id_1, int id_2) {
		this.id = id;
		this.id_1 = id_1;
		this.id_2 = id_2;
	}

	public VScriptupdateId(String url, String driver, String login, String password, String filename, int id, int id_1, int id_2) {
		this.url = url;
		this.driver = driver;
		this.login = login;
		this.password = password;
		this.filename = filename;
		this.id = id;
		this.id_1 = id_1;
		this.id_2 = id_2;
	}

	@Column(name = "URL", length = 16777215)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "DRIVER", length = 65535)
	public String getDriver() {
		return this.driver;
	}

	public void setDriver(String driver) {
		this.driver = driver;
	}

	@Column(name = "LOGIN", length = 65535)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "PASSWORD", length = 65535)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "FILENAME", length = 65535)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "PROJECT_ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "USERPROJECT_ID", nullable = false)
	public int getId_1() {
		return this.id_1;
	}

	public void setId_1(int id_1) {
		this.id_1 = id_1;
	}

	@Column(name = "PROJECTSCRIPT_ID", nullable = false)
	public int getId_2() {
		return this.id_2;
	}

	public void setId_2(int id_2) {
		this.id_2 = id_2;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof VScriptupdateId)) {
			return false;
		}
		VScriptupdateId castOther = (VScriptupdateId) other;

		return ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null && castOther.getUrl() != null && this.getUrl().equals(
				castOther.getUrl())))
				&& ((this.getDriver() == castOther.getDriver()) || (this.getDriver() != null && castOther.getDriver() != null && this.getDriver()
				.equals(castOther.getDriver())))
				&& ((this.getLogin() == castOther.getLogin()) || (this.getLogin() != null && castOther.getLogin() != null && this.getLogin().equals(
						castOther.getLogin())))
						&& ((this.getPassword() == castOther.getPassword()) || (this.getPassword() != null && castOther.getPassword() != null && this
						.getPassword().equals(castOther.getPassword())))
						&& ((this.getFilename() == castOther.getFilename()) || (this.getFilename() != null && castOther.getFilename() != null && this
						.getFilename().equals(castOther.getFilename())))
						&& (this.getId() == castOther.getId())
						&& (this.getId_1() == castOther.getId_1()) && (this.getId_2() == castOther.getId_2());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37 * result + (getDriver() == null ? 0 : this.getDriver().hashCode());
		result = 37 * result + (getLogin() == null ? 0 : this.getLogin().hashCode());
		result = 37 * result + (getPassword() == null ? 0 : this.getPassword().hashCode());
		result = 37 * result + (getFilename() == null ? 0 : this.getFilename().hashCode());
		result = 37 * result + this.getId();
		result = 37 * result + this.getId_1();
		result = 37 * result + this.getId_2();
		return result;
	}

}
