package webbati.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Avoir generated by hbm2java
 */
@Entity
@Table(name = "AVOIR")
@PrimaryKeyJoinColumn(name = "AFF_ID", referencedColumnName = "AFF_ID")
@SuppressWarnings("serial")
public class Avoir extends Affaire implements java.io.Serializable {

	private Facture facture;
	private Integer factureId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FAC_ID", insertable = false, updatable = false)
	public Facture getFacture() {
		return this.facture;
	}

	public void setFacture(Facture facture) {
		this.facture = facture;
	}

	@Column(name = "FAC_ID")
	public Integer getFactureId() {
		return this.factureId;
	}

	public void setFactureId(Integer factureId) {
		this.factureId = factureId;
	}
}
