package webbati.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Engin generated by hbm2java
 */
@Entity
@Table(name = "ENGIN")
@PrimaryKeyJoinColumn(name = "BIB_ID", referencedColumnName = "BIB_ID")
@SuppressWarnings("serial")
public abstract class Engin extends Bibliotheque implements java.io.Serializable {

	private String immatriculation;
	private Date immatriculationDate;

	@Column(name = "ENG_IMMATRICULATION", length = 25)
	public String getImmatriculation() {
		return this.immatriculation;
	}

	public void setImmatriculation(String immatriculation) {
		this.immatriculation = immatriculation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENG_IMMATRICULATION_DATE", length = 10)
	public Date getImmatriculationDate() {
		return this.immatriculationDate;
	}

	public void setImmatriculationDate(Date immatriculationDate) {
		this.immatriculationDate = immatriculationDate;
	}
}
