package webbati.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Reglement generated by hbm2java
 */
@Entity
@Table(name = "REGLEMENT")
@SuppressWarnings("serial")
public class Reglement implements java.io.Serializable {

	private Integer id;
	private Set<EcheancierReglement> echeancierReglements = new HashSet<EcheancierReglement>(0);
	private Integer modePaiementId;
	private ModePaiement modePaiement;
	private String code;
	private String descriptif;
	private Date datePaiement;
	private String banque;
	private String numCheque;

	public Reglement() {
	}

	public Reglement(Set<EcheancierReglement> echeancierReglements) {
		this.echeancierReglements = echeancierReglements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "REG_ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reglement")
	public Set<EcheancierReglement> getEcheancierReglements() {
		return this.echeancierReglements;
	}

	public void setEcheancierReglements(Set<EcheancierReglement> echeancierReglements) {
		this.echeancierReglements = echeancierReglements;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MP_ID", nullable = false, insertable = false, updatable = false)
	public ModePaiement getModePaiement() {
		return this.modePaiement;
	}

	public void setModePaiement(ModePaiement modePaiement) {
		this.modePaiement = modePaiement;
	}

	/**
	 * Retourne le champ modePaiementId.
	 * 
	 * @return le modePaiementId
	 */
	@Column(name = "MP_ID", nullable = false)
	public Integer getModePaiementId() {
		return modePaiementId;
	}

	/**
	 * Met à jour le champ modePaiementId.
	 * 
	 * @param pModePaiementId le modePaiementId à mettre à jour
	 */
	public void setModePaiementId(Integer pModePaiementId) {
		modePaiementId = pModePaiementId;
	}

	/**
	 * Retourne le champ code.
	 * 
	 * @return le code
	 */
	@Column(name = "REG_CODE")
	public String getCode() {
		return code;
	}

	/**
	 * Met à jour le champ code.
	 * 
	 * @param pCode le code à mettre à jour
	 */
	public void setCode(String pCode) {
		code = pCode;
	}

	/**
	 * Retourne le champ descriptif.
	 * 
	 * @return le descriptif
	 */
	@Column(name = "REG_DESCRIPTIF")
	public String getDescriptif() {
		return descriptif;
	}

	/**
	 * Met à jour le champ descriptif.
	 * 
	 * @param pDescriptif le descriptif à mettre à jour
	 */
	public void setDescriptif(String pDescriptif) {
		descriptif = pDescriptif;
	}

	/**
	 * Retourne le champ datePaiement.
	 * 
	 * @return le datePaiement
	 */
	@Column(name = "REG_DATE_PAIEMENT")
	public Date getDatePaiement() {
		return datePaiement;
	}

	/**
	 * Met à jour le champ datePaiement.
	 * 
	 * @param pDatePaiement le datePaiement à mettre à jour
	 */
	public void setDatePaiement(Date pDatePaiement) {
		datePaiement = pDatePaiement;
	}

	/**
	 * Retourne le champ banque.
	 * 
	 * @return le banque
	 */
	@Column(name = "REG_BANQUE")
	public String getBanque() {
		return banque;
	}

	/**
	 * Met à jour le champ banque.
	 * 
	 * @param pBanque le banque à mettre à jour
	 */
	public void setBanque(String pBanque) {
		banque = pBanque;
	}

	/**
	 * Retourne le champ numCheque.
	 * 
	 * @return le numCheque
	 */
	@Column(name = "REG_NUM_CHEQUE")
	public String getNumCheque() {
		return numCheque;
	}

	/**
	 * Met à jour le champ numCheque.
	 * 
	 * @param pNumCheque le numCheque à mettre à jour
	 */
	public void setNumCheque(String pNumCheque) {
		numCheque = pNumCheque;
	}
}
