package webbati.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Tache generated by hbm2java
 */
@Entity
@Table(name = "TACHE_LOT")
@PrimaryKeyJoinColumn(name = "BIB_ID", referencedColumnName = "BIB_ID")
@SuppressWarnings("serial")
public abstract class TacheLot extends Bibliotheque implements java.io.Serializable {

	private Boolean prixVenteFixe;
	private Float beneficeMx;
	private Float fraisGenerauxMx;
	private Float beneficeMo;
	private Float fraisGenerauxMo;
	private Float beneficeSt;
	private Float fraisGenerauxSt;
	private Float beneficeEng;
	private Float fraisGenerauxEng;
	private Boolean isLot;

	@Column(name = "TAC_PRIX_VENTE_FIXE")
	public Boolean getPrixVenteFixe() {
		return this.prixVenteFixe;
	}

	public void setPrixVenteFixe(Boolean prixVenteFixe) {
		this.prixVenteFixe = prixVenteFixe;
	}

	@Column(name = "TAC_IS_LOT")
	public Boolean getIsLot() {
		return this.isLot;
	}

	public void setIsLot(Boolean isLot) {
		this.isLot = isLot;
	}

	@Column(name = "TAC_BENEFICE_MX", precision = 6, scale = 3)
	public Float getBeneficeMx() {
		return this.beneficeMx;
	}

	public void setBeneficeMx(Float beneficeMx) {
		this.beneficeMx = beneficeMx;
	}

	@Column(name = "TAC_FRAIS_GENERAUX_MX", precision = 6, scale = 3)
	public Float getFraisGenerauxMx() {
		return this.fraisGenerauxMx;
	}

	public void setFraisGenerauxMx(Float fraisGenerauxMx) {
		this.fraisGenerauxMx = fraisGenerauxMx;
	}

	@Column(name = "TAC_BENEFICE_MO", precision = 6, scale = 3)
	public Float getBeneficeMo() {
		return this.beneficeMo;
	}

	public void setBeneficeMo(Float beneficeMo) {
		this.beneficeMo = beneficeMo;
	}

	@Column(name = "TAC_FRAIS_GENERAUX_MO", precision = 6, scale = 3)
	public Float getFraisGenerauxMo() {
		return this.fraisGenerauxMo;
	}

	public void setFraisGenerauxMo(Float fraisGenerauxMo) {
		this.fraisGenerauxMo = fraisGenerauxMo;
	}

	@Column(name = "TAC_BENEFICE_ST", precision = 6, scale = 3)
	public Float getBeneficeSt() {
		return this.beneficeSt;
	}

	public void setBeneficeSt(Float beneficeSt) {
		this.beneficeSt = beneficeSt;
	}

	@Column(name = "TAC_FRAIS_GENERAUX_ST", precision = 6, scale = 3)
	public Float getFraisGenerauxSt() {
		return this.fraisGenerauxSt;
	}

	public void setFraisGenerauxSt(Float fraisGenerauxSt) {
		this.fraisGenerauxSt = fraisGenerauxSt;
	}

	@Column(name = "TAC_BENEFICE_ENG", precision = 6, scale = 3)
	public Float getBeneficeEng() {
		return this.beneficeEng;
	}

	public void setBeneficeEng(Float beneficeEng) {
		this.beneficeEng = beneficeEng;
	}

	@Column(name = "TAC_FRAIS_GENERAUX_ENG", precision = 6, scale = 3)
	public Float getFraisGenerauxEng() {
		return this.fraisGenerauxEng;
	}

	public void setFraisGenerauxEng(Float fraisGenerauxEng) {
		this.fraisGenerauxEng = fraisGenerauxEng;
	}
}
