package admin.api.metier.id;

// Generated 6 mars 2014 20:30:26 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserprojectId generated by hbm2java
 */
@Embeddable
@SuppressWarnings("serial")
public class UserprojectId implements java.io.Serializable {

	private int useId;
	private int proId;

	/**
	 * 
	 * Constructeur.
	 */
	public UserprojectId() {
	}

	/**
	 * 
	 * Constructeur.
	 * 
	 * @param pUseId user Id
	 * @param pProId project Id
	 */
	public UserprojectId(int pUseId, int pProId) {
		this.useId = pUseId;
		this.proId = pProId;
	}

	/**
	 * Get UseId
	 * 
	 * @return UseId
	 */
	@Column(name = "USE_ID", nullable = false)
	public int getUseId() {
		return this.useId;
	}

	/**
	 * Set UseId
	 * 
	 * @param pUseId UseId
	 */
	public void setUseId(int pUseId) {
		this.useId = pUseId;
	}

	/**
	 * Get proId
	 * 
	 * @return proId
	 */
	@Column(name = "PRO_ID", nullable = false)
	public int getProId() {
		return this.proId;
	}

	/**
	 * Set proId
	 * 
	 * @param pProId proId
	 */
	public void setProId(int pProId) {
		this.proId = pProId;
	}

	@Override
	public boolean equals(Object pOther) {
		if ((this == pOther)) {
			return true;
		}
		if ((pOther == null)) {
			return false;
		}
		if (!(pOther instanceof UserprojectId)) {
			return false;
		}
		UserprojectId castOther = (UserprojectId) pOther;

		return (this.getUseId() == castOther.getUseId()) && (this.getProId() == castOther.getProId());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUseId();
		result = 37 * result + this.getProId();
		return result;
	}

}
