package webbati.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Acompte generated by hbm2java
 */
@Entity
@Table(name = "ACOMPTE")
@PrimaryKeyJoinColumn(name = "AFF_ID", referencedColumnName = "AFF_ID")
@SuppressWarnings("serial")
public class Acompte extends Affaire implements java.io.Serializable {

	private Devis devis;
	private Integer devisId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEV_ID", insertable = false, updatable = false)
	public Devis getDevis() {
		return this.devis;
	}

	public void setDevis(Devis devis) {
		this.devis = devis;
	}

	@Column(name = "DEV_ID")
	public Integer getDevisId() {
		return this.devisId;
	}

	public void setDevisId(Integer devisId) {
		this.devisId = devisId;
	}
}
