package webbati.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import common.api.metier.ejb.ILigneEjb;

/**
 * Bibliotheque generated by hbm2java
 */
@Entity
@Table(name = "BIBLIOTHEQUE")
@Inheritance(strategy = InheritanceType.JOINED)
@SuppressWarnings("serial")
public abstract class Bibliotheque implements java.io.Serializable, ILigneEjb {

	private Integer id;
	private Famille famille;
	private Integer familleId;
	private Tva tva;
	private Integer tvaId;
	private Image image;
	private Integer imageId;
	private Binaire binaireByBinDescriptif;
	private Integer binaireByBinDescriptifId;
	private Binaire binaireByBinNotes;
	private Integer binaireByBinNotesId;
	private Binaire binaireByBinDescTechinique;
	private Integer binaireByBinDescTechiniqueId;
	private Binaire binaireByBinDescCommercial;
	private Integer binaireByBinDescCommercialId;
	private String code;
	private String motCle;
	private String numSerie;
	private String unite;
	private Float prixAchatUnitaire;
	private Float fraisGeneraux;
	private Float benefice;
	private Date dateCreation;
	private Date dateMaj;
	private String barCode;
	private Binaire binaireByBinMetre;
	private Integer binaireByBinMetreId;
	private Etude etude;
	private Integer etudeId;
	private Bibliotheque bibOrigin;
	private Integer bibOriginId;
	private Bibliotheque bibParent;
	private Integer bibParentId;
	private Integer borneGauche;
	private Integer borneDroite;
	private Integer niveau;
	private Float quantite;

	@Override
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BIB_ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	@Override
	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FAM_ID", insertable = false, updatable = false)
	public Famille getFamille() {
		return this.famille;
	}

	public void setFamille(Famille famille) {
		this.famille = famille;
	}

	@Column(name = "FAM_ID")
	public Integer getFamilleId() {
		return this.familleId;
	}

	public void setFamilleId(Integer familleId) {
		this.familleId = familleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TVA_ID", nullable = false, insertable = false, updatable = false)
	public Tva getTva() {
		return this.tva;
	}

	public void setTva(Tva tva) {
		this.tva = tva;
	}

	@Column(name = "TVA_ID", nullable = false)
	public Integer getTvaId() {
		return this.tvaId;
	}

	public void setTvaId(Integer tvaId) {
		this.tvaId = tvaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IMG_IMAGE", insertable = false, updatable = false)
	public Image getImage() {
		return this.image;
	}

	public void setImage(Image image) {
		this.image = image;
	}

	@Column(name = "IMG_IMAGE")
	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BIN_DESCRIPTIF", insertable = false, updatable = false)
	public Binaire getBinaireByBinDescriptif() {
		return this.binaireByBinDescriptif;
	}

	public void setBinaireByBinDescriptif(Binaire binaireByBinDescriptif) {
		this.binaireByBinDescriptif = binaireByBinDescriptif;
	}

	@Column(name = "BIN_DESCRIPTIF")
	public Integer getDescriptifId() {
		return this.binaireByBinDescriptifId;
	}

	public void setDescriptifId(Integer binaireByBinDescriptifId) {
		this.binaireByBinDescriptifId = binaireByBinDescriptifId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BIN_NOTES", insertable = false, updatable = false)
	public Binaire getBinaireByBinNotes() {
		return this.binaireByBinNotes;
	}

	public void setBinaireByBinNotes(Binaire binaireByBinNotes) {
		this.binaireByBinNotes = binaireByBinNotes;
	}

	@Column(name = "BIN_NOTES")
	public Integer getNotesId() {
		return this.binaireByBinNotesId;
	}

	public void setNotesId(Integer binaireByBinNotesId) {
		this.binaireByBinNotesId = binaireByBinNotesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BIN_DESC_TECHINIQUE", insertable = false, updatable = false)
	public Binaire getBinaireByBinDescTechinique() {
		return this.binaireByBinDescTechinique;
	}

	public void setBinaireByBinDescTechinique(Binaire binaireByBinDescTechinique) {
		this.binaireByBinDescTechinique = binaireByBinDescTechinique;
	}

	@Column(name = "BIN_DESC_TECHINIQUE")
	public Integer getDescriptionTechniqueId() {
		return this.binaireByBinDescTechiniqueId;
	}

	public void setDescriptionTechniqueId(Integer binaireByBinDescTechiniqueId) {
		this.binaireByBinDescTechiniqueId = binaireByBinDescTechiniqueId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BIN_DESC_COMMERCIAL", insertable = false, updatable = false)
	public Binaire getBinaireByBinDescCommercial() {
		return this.binaireByBinDescCommercial;
	}

	public void setBinaireByBinDescCommercial(Binaire binaireByBinDescCommercial) {
		this.binaireByBinDescCommercial = binaireByBinDescCommercial;
	}

	@Column(name = "BIN_DESC_COMMERCIAL")
	public Integer getDescriptionCommercialeId() {
		return this.binaireByBinDescCommercialId;
	}

	public void setDescriptionCommercialeId(Integer binaireByBinDescCommercialId) {
		this.binaireByBinDescCommercialId = binaireByBinDescCommercialId;
	}

	@Column(name = "BIB_CODE", length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "BIB_MOT_CLE", length = 20)
	public String getMotCle() {
		return this.motCle;
	}

	public void setMotCle(String motCle) {
		this.motCle = motCle;
	}

	@Column(name = "BIB_NUM_SERIE", length = 20)
	public String getNumSerie() {
		return this.numSerie;
	}

	public void setNumSerie(String numSerie) {
		this.numSerie = numSerie;
	}

	@Column(name = "BIB_UNITE", length = 10)
	public String getUnite() {
		return this.unite;
	}

	public void setUnite(String unite) {
		this.unite = unite;
	}

	@Column(name = "BIB_PRIX_ACHAT", precision = 8)
	public Float getPrixAchatUnitaire() {
		return this.prixAchatUnitaire;
	}

	public void setPrixAchatUnitaire(Float prixAchat) {
		this.prixAchatUnitaire = prixAchat;
	}

	@Column(name = "BIB_FRAIS_GENERAUX", precision = 5)
	public Float getFraisGeneraux() {
		return this.fraisGeneraux;
	}

	public void setFraisGeneraux(Float fraisGeneraux) {
		this.fraisGeneraux = fraisGeneraux;
	}

	@Column(name = "BIB_BENEFICE", precision = 5)
	public Float getBenefice() {
		return this.benefice;
	}

	public void setBenefice(Float benefice) {
		this.benefice = benefice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BIB_DATE_CREATION", length = 19)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BIB_DATE_MAJ", length = 19)
	public Date getDateMaj() {
		return this.dateMaj;
	}

	public void setDateMaj(Date dateMaj) {
		this.dateMaj = dateMaj;
	}

	@Column(name = "BIB_BAR_CODE", length = 50)
	public String getBarCode() {
		return this.barCode;
	}

	public void setBarCode(String barCode) {
		this.barCode = barCode;
	}

	// Spécification pour élément étude
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BIN_METRE", insertable = false, updatable = false)
	public Binaire getBinaireByBinMetre() {
		return this.binaireByBinMetre;
	}

	public void setBinaireByBinMetre(Binaire binaireByBinMetre) {
		this.binaireByBinMetre = binaireByBinMetre;
	}

	@Column(name = "BIN_METRE")
	public Integer getMetreId() {
		return this.binaireByBinMetreId;
	}

	public void setMetreId(Integer binaireByBinMetreId) {
		this.binaireByBinMetreId = binaireByBinMetreId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ETU_ID", insertable = false, updatable = false)
	public Etude getEtude() {
		return this.etude;
	}

	public void setEtude(Etude etude) {
		this.etude = etude;
	}

	@Column(name = "ETU_ID")
	public Integer getEtudeId() {
		return this.etudeId;
	}

	public void setEtudeId(Integer etudeId) {
		this.etudeId = etudeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BIB_ORIGIN", insertable = false, updatable = false)
	public Bibliotheque getBibOrigin() {
		return this.bibOrigin;
	}

	public void setBibOrigin(Bibliotheque bibOrigin) {
		this.bibOrigin = bibOrigin;
	}

	@Column(name = "BIB_ORIGIN")
	public Integer getBibOriginId() {
		return this.bibOriginId;
	}

	public void setBibOriginId(Integer bibOriginId) {
		this.bibOriginId = bibOriginId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BIB_PARENT", insertable = false, updatable = false)
	public Bibliotheque getSuperParent() {
		return this.bibParent;
	}

	public void setSuperParent(Bibliotheque bibParent) {
		this.bibParent = bibParent;
	}

	@Override
	@Column(name = "BIB_PARENT")
	public Integer getSuperParentId() {
		return this.bibParentId;
	}

	@Override
	public void setSuperParentId(Integer bibParentId) {
		this.bibParentId = bibParentId;
	}

	@Override
	@Column(name = "BIB_BORNE_GAUCHE", precision = 7, scale = 0)
	public Integer getBorneGauche() {
		return this.borneGauche;
	}

	@Override
	public void setBorneGauche(Integer borneGauche) {
		this.borneGauche = borneGauche;
	}

	@Override
	@Column(name = "BIB_BORNE_DROITE", precision = 7, scale = 0)
	public Integer getBorneDroite() {
		return this.borneDroite;
	}

	@Override
	public void setBorneDroite(Integer borneDroite) {
		this.borneDroite = borneDroite;
	}

	@Override
	@Column(name = "BIB_NIVEAU", precision = 7, scale = 0)
	public Integer getNiveau() {
		return this.niveau;
	}

	@Override
	public void setNiveau(Integer niveau) {
		this.niveau = niveau;
	}

	@Column(name = "BIB_QUANTITE", precision = 11, scale = 3)
	public Float getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Float quantite) {
		this.quantite = quantite;
	}
}
