package webbati.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chantier generated by hbm2java
 */
@Entity
@Table(name = "CHANTIER")
@SuppressWarnings("serial")
public class Chantier implements java.io.Serializable {

	private Integer id;
	private Set<Affaire> affaires = new HashSet<Affaire>(0);

	public Chantier() {
	}

	public Chantier(Set<Affaire> affaires) {
		this.affaires = affaires;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CHT_ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chantier")
	public Set<Affaire> getAffaires() {
		return this.affaires;
	}

	public void setAffaires(Set<Affaire> affaires) {
		this.affaires = affaires;
	}

}
