package webbati.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Devis generated by hbm2java
 */
@Entity
@Table(name = "DEVIS")
@PrimaryKeyJoinColumn(name = "AFF_ID", referencedColumnName = "AFF_ID")
@SuppressWarnings("serial")
public class Devis extends Affaire implements java.io.Serializable {

	private Set<Acompte> acomptes = new HashSet<Acompte>(0);
	private Set<Situation> situations = new HashSet<Situation>(0);
	private Set<Facture> factures = new HashSet<Facture>(0);
	private Devis devis;
	private Integer devisId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEV_SOURCE_ID", insertable = false, updatable = false)
	public Devis getDevis() {
		return this.devis;
	}

	public void setDevis(Devis devis) {
		this.devis = devis;
	}

	@Column(name = "DEV_SOURCE_ID")
	public Integer getDevisId() {
		return this.devisId;
	}

	public void setDevisId(Integer devisId) {
		this.devisId = devisId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "devis")
	public Set<Acompte> getAcomptes() {
		return this.acomptes;
	}

	public void setAcomptes(Set<Acompte> acomptes) {
		this.acomptes = acomptes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "devis")
	public Set<Situation> getSituations() {
		return this.situations;
	}

	public void setSituations(Set<Situation> situations) {
		this.situations = situations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "devis")
	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

}
