package webbati.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EcheancierReglement generated by hbm2java
 */
@Entity
@Table(name = "ECHEANCIER_REGLEMENT")
@SuppressWarnings("serial")
public class EcheancierReglement implements java.io.Serializable {

	private EcheancierReglementId id;
	private Reglement reglement;
	private Echeancier echeancier;
	private Float montant;

	public EcheancierReglement() {
	}

	public EcheancierReglement(EcheancierReglementId id, Reglement reglement, Echeancier echeancier) {
		this.id = id;
		this.reglement = reglement;
		this.echeancier = echeancier;
	}

	public EcheancierReglement(EcheancierReglementId id, Reglement reglement, Echeancier echeancier, Float montant) {
		this.id = id;
		this.reglement = reglement;
		this.echeancier = echeancier;
		this.montant = montant;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ECH_ID", nullable = false)),
		@AttributeOverride(name = "id_1", column = @Column(name = "REG_ID", nullable = false)) })
	public EcheancierReglementId getId() {
		return this.id;
	}

	public void setId(EcheancierReglementId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REG_ID", nullable = false, insertable = false, updatable = false)
	public Reglement getReglement() {
		return this.reglement;
	}

	public void setReglement(Reglement reglement) {
		this.reglement = reglement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ECH_ID", nullable = false, insertable = false, updatable = false)
	public Echeancier getEcheancier() {
		return this.echeancier;
	}

	public void setEcheancier(Echeancier echeancier) {
		this.echeancier = echeancier;
	}

	@Column(name = "ERG_MONTANT", precision = 8)
	public Float getMontant() {
		return this.montant;
	}

	public void setMontant(Float montant) {
		this.montant = montant;
	}

}
