package webbati.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pays generated by hbm2java
 */
@Entity
@Table(name = "PAYS")
@SuppressWarnings("serial")
public class Pays implements java.io.Serializable {

	private Integer id;
	private String libelle;
	private Set<Coordonneecnt> coordonneecnts = new HashSet<Coordonneecnt>(0);

	public Pays() {
	}

	public Pays(String libelle, Set<Coordonneecnt> coordonneecnts) {
		this.libelle = libelle;
		this.coordonneecnts = coordonneecnts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PAY_ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PAY_LIBELLE", length = 30)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pays")
	public Set<Coordonneecnt> getCoordonneecnts() {
		return this.coordonneecnts;
	}

	public void setCoordonneecnts(Set<Coordonneecnt> coordonneecnts) {
		this.coordonneecnts = coordonneecnts;
	}

}
