package batifree.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Codification generated by hbm2java
 */
@Entity
@Table(name = "CODIFICATION")
@SuppressWarnings("serial")
public class Codification implements java.io.Serializable {

	private Integer id;
	private Integer type;
	private String formatage;
	private Long compteur;

	public Codification() {
	}

	public Codification(Integer type, String formatage, Long compteur) {
		this.type = type;
		this.formatage = formatage;
		this.compteur = compteur;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "COD_ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "COD_TYPE")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "COD_FORMATAGE", length = 50)
	public String getFormatage() {
		return this.formatage;
	}

	public void setFormatage(String formatage) {
		this.formatage = formatage;
	}

	@Column(name = "COD_COMPTEUR")
	public Long getCompteur() {
		return this.compteur;
	}

	public void setCompteur(Long compteur) {
		this.compteur = compteur;
	}

}
