package batifree.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "CONTACT")
@Inheritance(strategy = InheritanceType.JOINED)
@SuppressWarnings("serial")
public class Contact implements java.io.Serializable {

	private Integer id;
	private Categorie categorie;
	private Integer categorieId;
	private Binaire binaireByBinRemarques;
	private Integer binaireByBinRemarquesId;
	private Binaire binaireByBinRappelMotif;
	private Integer binaireByBinRappelMotifId;
	private Activite activite;
	private Integer activiteId;
	private Coordonneecnt coordonneecnt;
	private Integer coordonneecntId;
	private String code;
	private String nomSociete;
	private Date dateCreation;
	private Date dateMaj;
	private String codeNaf;
	private String siren;
	private String tvaIntra;
	private Date rappelDate;
	private Boolean hide;
	private Set<Detailcnt> detailcnts = new HashSet<Detailcnt>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CNT_ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAT_ID", insertable = false, updatable = false)
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@Column(name = "CAT_ID")
	public Integer getCategorieId() {
		return this.categorieId;
	}

	public void setCategorieId(Integer categorieId) {
		this.categorieId = categorieId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BIN_REMARQUES", insertable = false, updatable = false)
	public Binaire getBinaireByBinRemarques() {
		return this.binaireByBinRemarques;
	}

	public void setBinaireByBinRemarques(Binaire binaireByBinRemarques) {
		this.binaireByBinRemarques = binaireByBinRemarques;
	}

	@Column(name = "BIN_REMARQUES")
	public Integer getRemarquesId() {
		return this.binaireByBinRemarquesId;
	}

	public void setRemarquesId(Integer binaireByBinRemarquesId) {
		this.binaireByBinRemarquesId = binaireByBinRemarquesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BIN_RAPPEL_MOTIF", insertable = false, updatable = false)
	public Binaire getBinaireByBinRappelMotif() {
		return this.binaireByBinRappelMotif;
	}

	public void setBinaireByBinRappelMotif(Binaire binaireByBinRappelMotif) {
		this.binaireByBinRappelMotif = binaireByBinRappelMotif;
	}

	@Column(name = "BIN_RAPPEL_MOTIF")
	public Integer getRappelMotifId() {
		return this.binaireByBinRappelMotifId;
	}

	public void setRappelMotifId(Integer binaireByBinRappelMotifId) {
		this.binaireByBinRappelMotifId = binaireByBinRappelMotifId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACT_ID", insertable = false, updatable = false)
	public Activite getActivite() {
		return this.activite;
	}

	public void setActivite(Activite activite) {
		this.activite = activite;
	}

	@Column(name = "ACT_ID")
	public Integer getActiviteId() {
		return this.activiteId;
	}

	public void setActiviteId(Integer activiteId) {
		this.activiteId = activiteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COO_ID", insertable = false, updatable = false)
	public Coordonneecnt getCoordonneecnt() {
		return this.coordonneecnt;
	}

	public void setCoordonneecnt(Coordonneecnt coordonneecnt) {
		this.coordonneecnt = coordonneecnt;
	}

	@Column(name = "COO_ID")
	public Integer getCoordonneId() {
		return this.coordonneecntId;
	}

	public void setCoordonneId(Integer coordonneecntId) {
		this.coordonneecntId = coordonneecntId;
	}

	@Column(name = "CNT_CODE", length = 25)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "CNT_NOM_SOCIETE", length = 40)
	public String getNomSociete() {
		return this.nomSociete;
	}

	public void setNomSociete(String nomSociete) {
		this.nomSociete = nomSociete;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_DATE_CREATION", length = 19)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_DATE_MAJ", length = 19)
	public Date getDateMaj() {
		return this.dateMaj;
	}

	public void setDateMaj(Date dateMaj) {
		this.dateMaj = dateMaj;
	}

	@Column(name = "CNT_CODE_NAF", length = 6)
	public String getCodeNaf() {
		return this.codeNaf;
	}

	public void setCodeNaf(String codeNaf) {
		this.codeNaf = codeNaf;
	}

	@Column(name = "CNT_SIREN", length = 14)
	public String getSiren() {
		return this.siren;
	}

	public void setSiren(String siren) {
		this.siren = siren;
	}

	@Column(name = "CNT_TVA_INTRA", length = 13)
	public String getTvaIntra() {
		return this.tvaIntra;
	}

	public void setTvaIntra(String tvaIntra) {
		this.tvaIntra = tvaIntra;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_RAPPEL_DATE", length = 10)
	public Date getRappelDate() {
		return this.rappelDate;
	}

	public void setRappelDate(Date rappelDate) {
		this.rappelDate = rappelDate;
	}

	@Column(name = "CNT_HIDE")
	public Boolean getHide() {
		return this.hide;
	}

	public void setHide(Boolean hide) {
		this.hide = hide;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contact")
	public Set<Detailcnt> getDetailcnts() {
		return this.detailcnts;
	}

	public void setDetailcnts(Set<Detailcnt> detailcnts) {
		this.detailcnts = detailcnts;
	}

}
