package batifree.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detailcnt generated by hbm2java
 */
@Entity
@Table(name = "DETAILCNT")
@SuppressWarnings("serial")
public class Detailcnt implements java.io.Serializable {

	private Integer id;
	private Contact contact;
	private Integer contactId;
	private Coordonneecnt coordonneecnt;
	private Integer coordonneecntId;
	private Boolean defaut;
	private Short ordre;
	private String fonction;

	public Detailcnt() {
	}

	public Detailcnt(Contact contact) {
		this.contact = contact;
	}

	public Detailcnt(Contact contact, Coordonneecnt coordonneecnt, Boolean defaut, Short ordre, String fonction) {
		this.contact = contact;
		this.coordonneecnt = coordonneecnt;
		this.defaut = defaut;
		this.ordre = ordre;
		this.fonction = fonction;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "DET_ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CNT_ID", nullable = false, insertable = false, updatable = false)
	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	@Column(name = "CNT_ID", nullable = false)
	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COO_ID", insertable = false, updatable = false)
	public Coordonneecnt getCoordonneecnt() {
		return this.coordonneecnt;
	}

	public void setCoordonneecnt(Coordonneecnt coordonneecnt) {
		this.coordonneecnt = coordonneecnt;
	}

	@Column(name = "COO_ID")
	public Integer getCoordonneeId() {
		return this.coordonneecntId;
	}

	public void setCoordonneeId(Integer coordonneecntId) {
		this.coordonneecntId = coordonneecntId;
	}

	@Column(name = "DET_DEFAUT")
	public Boolean getDefaut() {
		return this.defaut;
	}

	public void setDefaut(Boolean defaut) {
		this.defaut = defaut;
	}

	@Column(name = "DET_ORDRE")
	public Short getOrdre() {
		return this.ordre;
	}

	public void setOrdre(Short ordre) {
		this.ordre = ordre;
	}

	@Column(name = "DET_FONCTION", length = 40)
	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

}
