package batifree.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Diverscnt generated by hbm2java
 */
@Entity
@Table(name = "DIVERSCNT")
@PrimaryKeyJoinColumn(name = "CNT_ID", referencedColumnName = "CNT_ID")
@SuppressWarnings("serial")
public class Diverscnt extends Contact implements java.io.Serializable {

	private Set<Groupecnt> groupecnts = new HashSet<Groupecnt>(0);

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "GROUPECNT_DIVERSCNT", joinColumns = { @JoinColumn(name = "CNT_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "GRP_ID", nullable = false, updatable = false) })
	public Set<Groupecnt> getGroupecnts() {
		return this.groupecnts;
	}

	public void setGroupecnts(Set<Groupecnt> groupecnts) {
		this.groupecnts = groupecnts;
	}

}
