package batifree.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Echeancier generated by hbm2java
 */
@Entity
@Table(name = "ECHEANCIER")
@SuppressWarnings("serial")
public class Echeancier implements java.io.Serializable {

	private Integer id;
	private Affaire affaire;
	private Integer affaireId;
	private Set<EcheancierReglement> echeancierReglements = new HashSet<EcheancierReglement>(0);

	public Echeancier() {
	}

	public Echeancier(Affaire affaire, Set<EcheancierReglement> echeancierReglements) {
		this.affaire = affaire;
		this.echeancierReglements = echeancierReglements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ECH_ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AFF_ID", insertable = false, updatable = false)
	public Affaire getAffaire() {
		return this.affaire;
	}

	public void setAffaire(Affaire affaire) {
		this.affaire = affaire;
	}

	@Column(name = "AFF_ID")
	public Integer getAffaireId() {
		return this.affaireId;
	}

	public void setAffaireId(Integer affaireId) {
		this.affaireId = affaireId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "echeancier")
	public Set<EcheancierReglement> getEcheancierReglements() {
		return this.echeancierReglements;
	}

	public void setEcheancierReglements(Set<EcheancierReglement> echeancierReglements) {
		this.echeancierReglements = echeancierReglements;
	}

}
