package batifree.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etat generated by hbm2java
 */
@Entity
@Table(name = "ETAT")
@SuppressWarnings("serial")
public class Etat implements java.io.Serializable {

	private Integer id;
	private String libelle;
	private Set<Affaire> affaires = new HashSet<Affaire>(0);

	public Etat() {
	}

	public Etat(String libelle, Set<Affaire> affaires) {
		this.libelle = libelle;
		this.affaires = affaires;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ETA_ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ETA_LIBELLE", length = 30)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etat")
	public Set<Affaire> getAffaires() {
		return this.affaires;
	}

	public void setAffaires(Set<Affaire> affaires) {
		this.affaires = affaires;
	}

}
