package batifree.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etude generated by hbm2java
 */
@Entity
@Table(name = "ETUDE")
@SuppressWarnings("serial")
public class Etude implements java.io.Serializable {

	private Integer id;
	private Affaire affaire;
	private Integer affaireId;
	private Tva tva;
	private Integer tvaId;
	private Set<Bibliotheque> bibliotheques = new HashSet<Bibliotheque>(0);

	public Etude() {
	}

	public Etude(Affaire affaire) {
		this.affaire = affaire;
	}

	public Etude(Affaire affaire, Tva tva, Set<Affaire> affaires, Set<Bibliotheque> ligneetudes) {
		this.affaire = affaire;
		this.tva = tva;
		this.bibliotheques = ligneetudes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ETU_ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AFF_ID", nullable = false, insertable = false, updatable = false)
	public Affaire getAffaire() {
		return this.affaire;
	}

	public void setAffaire(Affaire affaire) {
		this.affaire = affaire;
	}

	@Column(name = "AFF_ID", nullable = false)
	public Integer getAffaireId() {
		return this.affaireId;
	}

	public void setAffaireId(Integer affaireId) {
		this.affaireId = affaireId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TVA_DEFAUT", insertable = false, updatable = false)
	public Tva getTva() {
		return this.tva;
	}

	public void setTva(Tva tva) {
		this.tva = tva;
	}

	@Column(name = "TVA_DEFAUT")
	public Integer getTvaDefaultId() {
		return this.tvaId;
	}

	public void setTvaDefaultId(Integer tvaId) {
		this.tvaId = tvaId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etude")
	public Set<Bibliotheque> getBibliotheques() {
		return this.bibliotheques;
	}

	public void setBibliotheques(Set<Bibliotheque> bibliotheques) {
		this.bibliotheques = bibliotheques;
	}

}
