package batifree.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FournisseurMateriaux generated by hbm2java
 */
@Entity
@Table(name = "FOURNISSEUR_MATERIAUX")
@SuppressWarnings("serial")
public class FournisseurMateriaux implements java.io.Serializable {

	private FournisseurMateriauxId id;
	private Fournisseur fournisseur;
	private Materiaux materiaux;
	private Float prixTarif;
	private Float remise;
	private Float qteMini;

	public FournisseurMateriaux() {
	}

	public FournisseurMateriaux(FournisseurMateriauxId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "BIB_ID", nullable = false)),
		@AttributeOverride(name = "id_1", column = @Column(name = "CNT_ID", nullable = false)) })
	public FournisseurMateriauxId getId() {
		return this.id;
	}

	public void setId(FournisseurMateriauxId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CNT_ID", nullable = false, insertable = false, updatable = false)
	public Fournisseur getFournisseur() {
		return this.fournisseur;
	}

	public void setFournisseur(Fournisseur fournisseur) {
		this.fournisseur = fournisseur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BIB_ID", nullable = false, insertable = false, updatable = false)
	public Materiaux getMateriaux() {
		return this.materiaux;
	}

	public void setMateriaux(Materiaux materiaux) {
		this.materiaux = materiaux;
	}

	@Column(name = "FRNMX_PRIX_TARIF", precision = 8)
	public Float getPrixTarif() {
		return this.prixTarif;
	}

	public void setPrixTarif(Float prixTarif) {
		this.prixTarif = prixTarif;
	}

	@Column(name = "FRNMX_REMISE", precision = 5)
	public Float getRemise() {
		return this.remise;
	}

	public void setRemise(Float remise) {
		this.remise = remise;
	}

	@Column(name = "FRNMX_QTE_MINI", precision = 9, scale = 3)
	public Float getQuantiteMini() {
		return this.qteMini;
	}

	public void setQuantiteMini(Float qteMini) {
		this.qteMini = qteMini;
	}

}
