package batifree.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "IMAGE")
@SuppressWarnings("serial")
public class Image implements java.io.Serializable {

	private Integer id;
	private byte[] objet;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IMG_ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "IMG_OBJET")
	public byte[] getObjet() {
		return this.objet;
	}

	public void setObjet(byte[] objet) {
		this.objet = objet;
	}
}
