package webbati.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "CLIENT")
@PrimaryKeyJoinColumn(name = "CNT_ID", referencedColumnName = "CNT_ID")
@SuppressWarnings("serial")
public class Client extends Contact implements java.io.Serializable {

	private Boolean prospect;
	private Float montantPlafond;
	private Set<Affaire> affaires = new HashSet<Affaire>(0);
	private Set<Coordonneecnt> coordonneecnts = new HashSet<Coordonneecnt>(0);

	@Column(name = "CLI_PROSPECT")
	public Boolean getProspect() {
		return this.prospect;
	}

	public void setProspect(Boolean prospect) {
		this.prospect = prospect;
	}

	@Column(name = "CLI_MONTANT_PLAFOND", precision = 8)
	public Float getMontantPlafond() {
		return this.montantPlafond;
	}

	public void setMontantPlafond(Float montantPlafond) {
		this.montantPlafond = montantPlafond;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Affaire> getAffaires() {
		return this.affaires;
	}

	public void setAffaires(Set<Affaire> affaires) {
		this.affaires = affaires;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Coordonneecnt> getCoordonneecnts() {
		return this.coordonneecnts;
	}

	public void setCoordonneecnts(Set<Coordonneecnt> coordonneecnts) {
		this.coordonneecnts = coordonneecnts;
	}

}
