package webbati.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Fournisseur generated by hbm2java
 */
@Entity
@Table(name = "FOURNISSEUR")
@PrimaryKeyJoinColumn(name = "CNT_ID", referencedColumnName = "CNT_ID")
@SuppressWarnings("serial")
public class Fournisseur extends Contact implements java.io.Serializable {

	private Set<FournisseurMateriaux> fournisseurMateriauxes = new HashSet<FournisseurMateriaux>(0);
	private Set<Materiaux> materiauxes = new HashSet<Materiaux>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fournisseur")
	public Set<FournisseurMateriaux> getFournisseurMateriauxes() {
		return this.fournisseurMateriauxes;
	}

	public void setFournisseurMateriauxes(Set<FournisseurMateriaux> fournisseurMateriauxes) {
		this.fournisseurMateriauxes = fournisseurMateriauxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fournisseur")
	public Set<Materiaux> getMateriauxes() {
		return this.materiauxes;
	}

	public void setMateriauxes(Set<Materiaux> materiauxes) {
		this.materiauxes = materiauxes;
	}

}
