package webbati.api.metier.ejb;

// Generated 4 avr. 2014 20:19:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tva generated by hbm2java
 */
@Entity
@Table(name = "TVA")
@SuppressWarnings("serial")
public class Tva implements java.io.Serializable {

	private Integer id;
	private String libelle;
	private Float taux;
	private Boolean hide;
	private Set<Bibliotheque> bibliotheques = new HashSet<Bibliotheque>(0);
	private Set<Etude> etudes = new HashSet<Etude>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TVA_ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "TVA_LIBELLE", length = 30)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "TVA_TAUX", precision = 5)
	public Float getTaux() {
		return this.taux;
	}

	public void setTaux(Float taux) {
		this.taux = taux;
	}

	@Column(name = "TVA_HIDE")
	public Boolean getHide() {
		return this.hide;
	}

	public void setHide(Boolean hide) {
		this.hide = hide;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tva")
	public Set<Bibliotheque> getBibliotheques() {
		return this.bibliotheques;
	}

	public void setBibliotheques(Set<Bibliotheque> bibliotheques) {
		this.bibliotheques = bibliotheques;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tva")
	public Set<Etude> getEtudes() {
		return this.etudes;
	}

	public void setEtudes(Set<Etude> etudes) {
		this.etudes = etudes;
	}
}
