package admin.api.metier.ejb;

// Generated 3 mars 2014 23:09:58 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userappli generated by hbm2java
 */
@Entity
@Table(name = "USERAPPLI")
@SuppressWarnings("serial")
public class Userappli implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String mail;
	private Date dateCreate;
	private Date dateExpired;
	private Boolean locked;
	private Set<Userproject> userprojects = new HashSet<Userproject>(0);
	private Set<Role> roles = new HashSet<Role>(0);
	private Userappli userappliParent;
	private Integer userappliParentId;

	public Userappli() {
	}

	public Userappli(String username, String password, String mail, Date dateCreate, Date dateExpired, Boolean locked,
			Set<Userproject> userprojects, Set<Role> roles) {
		this.username = username;
		this.password = password;
		this.mail = mail;
		this.dateCreate = dateCreate;
		this.dateExpired = dateExpired;
		this.locked = locked;
		this.userprojects = userprojects;
		this.roles = roles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USE_ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "USE_USERNAME", length = 65535)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "USE_PASSWORD", length = 65535)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "USE_MAIL", length = 65535)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "USE_DATE_CREATE", length = 19)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "USE_DATE_EXPIRED", length = 19)
	public Date getDateExpired() {
		return this.dateExpired;
	}

	public void setDateExpired(Date dateExpired) {
		this.dateExpired = dateExpired;
	}

	@Column(name = "USE_LOCKED")
	public Boolean getLocked() {
		return this.locked;
	}

	public void setLocked(Boolean locked) {
		this.locked = locked;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userappli")
	public Set<Userproject> getUserprojects() {
		return this.userprojects;
	}

	public void setUserprojects(Set<Userproject> userprojects) {
		this.userprojects = userprojects;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "USERROLE", joinColumns = { @JoinColumn(name = "USE_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ROL_ID", nullable = false, updatable = false) })
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USE_PARENT", insertable = false, updatable = false)
	public Userappli getUserappliParent() {
		return this.userappliParent;
	}

	public void setUserappliParent(Userappli pUserappliParent) {
		this.userappliParent = pUserappliParent;
	}

	@Column(name = "USE_PARENT")
	public Integer getUserappliParentId() {
		return this.userappliParentId;
	}

	public void setUserappliParentId(Integer pUserappliParentId) {
		this.userappliParentId = pUserappliParentId;
	}

}
