package admin.api.metier.ejb;

// Generated 6 mars 2014 20:30:26 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import admin.api.metier.id.UserprojectId;

/**
 * Userproject generated by hbm2java
 */
@Entity
@Table(name = "USERPROJECT")
@SuppressWarnings("serial")
public class Userproject implements java.io.Serializable {

	private UserprojectId id;
	private Project project;
	private Projectscript projectscript;
	private Connectiondb connectiondb;
	private Userappli userappli;
	private String bdLogin;
	private String bdPassword;
	private String bdDbname;
	private Integer projectscriptId;
	private Integer connectiondbId;

	public Userproject() {
	}

	public Userproject(UserprojectId id, Project project, Userappli userappli) {
		this.id = id;
		this.project = project;
		this.userappli = userappli;
	}

	public Userproject(UserprojectId id, Project project, Projectscript projectscript, Connectiondb connectiondb, Userappli userappli,
			String bdLogin, String bdPassword, String bdDbname) {
		this.id = id;
		this.project = project;
		this.projectscript = projectscript;
		this.connectiondb = connectiondb;
		this.userappli = userappli;
		this.bdLogin = bdLogin;
		this.bdPassword = bdPassword;
		this.bdDbname = bdDbname;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "useId", column = @Column(name = "USE_ID", nullable = false)),
	        @AttributeOverride(name = "proId", column = @Column(name = "PRO_ID", nullable = false)) })
	public UserprojectId getId() {
		return this.id;
	}

	public void setId(UserprojectId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRO_ID", nullable = false, insertable = false, updatable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PSR_ID", insertable = false, updatable = false)
	public Projectscript getProjectscript() {
		return this.projectscript;
	}

	@Column(name = "PSR_ID")
	public Integer getProjectscriptId() {
		return this.projectscriptId;
	}

	public void setProjectscript(Projectscript projectscript) {
		this.projectscript = projectscript;
	}

	public void setProjectscriptId(Integer projectscriptId) {
		this.projectscriptId = projectscriptId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CON_ID", insertable = false, updatable = false)
	public Connectiondb getConnectiondb() {
		return this.connectiondb;
	}

	public void setConnectiondb(Connectiondb connectiondb) {
		this.connectiondb = connectiondb;
	}

	@Column(name = "CON_ID")
	public Integer getConnectiondbId() {
		return this.connectiondbId;
	}

	public void setConnectiondbId(Integer connectiondbId) {
		this.connectiondbId = connectiondbId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USE_ID", nullable = false, insertable = false, updatable = false)
	public Userappli getUserappli() {
		return this.userappli;
	}

	public void setUserappli(Userappli userappli) {
		this.userappli = userappli;
	}

	@Column(name = "USP_BD_LOGIN", length = 65535)
	public String getBdLogin() {
		return this.bdLogin;
	}

	public void setBdLogin(String bdLogin) {
		this.bdLogin = bdLogin;
	}

	@Column(name = "USP_BD_PASSWORD", length = 65535)
	public String getBdPassword() {
		return this.bdPassword;
	}

	public void setBdPassword(String bdPassword) {
		this.bdPassword = bdPassword;
	}

	@Column(name = "USP_BD_DBNAME", length = 65535)
	public String getBdDbname() {
		return this.bdDbname;
	}

	public void setBdDbname(String bdDbname) {
		this.bdDbname = bdDbname;
	}

}
