package admin.api.metier.ejb;

// Generated 9 ao�t 2013 22:29:28 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VConnectiondb generated by hbm2java
 */
@Entity
@Table(name = "V_CONNECTIONDB")
@SuppressWarnings("serial")
public class VConnectiondb implements java.io.Serializable {

	private VConnectiondbId id;

	public VConnectiondb() {
	}

	public VConnectiondb(VConnectiondbId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "CON_ID", nullable = false)),
		@AttributeOverride(name = "driver", column = @Column(name = "CON_DRIVER", length = 65535)),
		@AttributeOverride(name = "url", column = @Column(name = "CON_URL", length = 65535)),
		@AttributeOverride(name = "dialect", column = @Column(name = "CON_DIALECT", length = 65535)),
		@AttributeOverride(name = "limitUserAlert", column = @Column(name = "CON_LIMIT_USER_ALERT")),
		@AttributeOverride(name = "rootLogin", column = @Column(name = "CON_ROOT_LOGIN", length = 65535)),
		@AttributeOverride(name = "rootPassword", column = @Column(name = "CON_ROOT_PASSWORD", length = 65535)),
		@AttributeOverride(name = "rootDbname", column = @Column(name = "CON_ROOT_DBNAME", length = 65535)),
		@AttributeOverride(name = "enabled", column = @Column(name = "CON_ENABLED")),
		@AttributeOverride(name = "userRestant", column = @Column(name = "NB_USER_RESTANT")) })
	public VConnectiondbId getId() {
		return this.id;
	}

	public void setId(VConnectiondbId id) {
		this.id = id;
	}

}
